### ISSUE TITLE
oasis 

### ISSUE THREAD

**Issue by n0faces** [relrelb/CPPS-PCL#14]
oasis seems to have patched. is it possible to change something to bypass it?

**Comment by relrelb** [comment]
Can you please explain in more details about the problem? Where does it exactly fail?

**Comment by n0faces** [comment]
when i login and make the bot follow this comes up. 

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/charles/Desktop/pcl/client.py", line 745, in _game
    thread.join()
  File "/home/charles/Desktop/pcl/client.py", line 23, in run
    super(_ExceptionThread, self).run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/charles/Desktop/pcl/client.py", line 51, in inner_handle
    self._callback(packet)
  File "/home/charles/Desktop/pcl/client.py", line 457, in _jr
    penguin = Penguin.from_player(player)
  File "/home/charles/Desktop/pcl/penguin.py", line 32, in from_player
    color = int(player[3], 16)
ValueError: invalid literal for int() with base 16: 'n****'

( i censored the last thing cause its a bit racist.) lmao

**Comment by n0faces** [comment]
also im not asking but id be overjoyed if u added these few new cpps from this list 
https://clubpenguincentral.co/cpps-list/

**Comment by relrelb** [comment]
Hey, I think this issue has been fixed by now.
